version: '3.4'
services:
  slack-radio:
    container_name: ${CONTAINER_NAME}
    build:
      dockerfile: Dockerfile-dev
      context: ./
    environment:
      - NODE_ENV=development
    restart: 'no'
    env_file:
      - ./.env
    volumes:
      - ./:/app
    ports:
      - 58587:58587
      - 58586:58586
      - 58585:58585
      - 8888:8888
