version: '3.4'
services:
  slack-radio:
    container_name: ${NODE_CONTAINER_NAME}
    build:
      dockerfile: Dockerfile-dev
      context: ./
    environment:
      - NODE_ENV=development
    restart: 'no'
    env_file:
      - ./.env
    volumes:
      - ./:/app
    ports:
      - 58587:58587
      - 58586:58586
      - 58585:58585
      - 8888:8888
    networks:
      sr_net:
        ipv4_address: 126.126.1.1

  slack-radio-mongo:
    env_file:
      - ./.env
    container_name: ${MONGO_CONTAINER_NAME}
    volumes:
      - ./data/mongodb:/data/db
    image: mongo:3.5
    restart: 'no'
    ports:
      - 27017:27017
    networks:
      sr_net:
        ipv4_address: 126.126.1.2

  slack-radio-redis:
    env_file:
      - ./.env
    container_name: ${REDIS_CONTAINER_NAME}
    volumes:
      - ./data/redis:/data
    image: redis:alpine
    restart: 'no'
    ports:
      - 6379:6379
    networks:
      sr_net:
        ipv4_address: 126.126.1.3

networks:
  sr_net:
    external:
      name: SrNet
