FROM node:carbon

RUN echo "deb http://ftp.fr.debian.org/debian jessie-backports main" >> /etc/apt/sources.list

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --fix-missing build-essential gcc g++ ca-certificates libmp3lame-dev libxml2-dev libshout-dev libvorbis-dev tcl expect python-dev \
 && rm -rf /var/lib/apt/lists/*

RUN mkdir /var/log/ices
RUN mkdir /etc/ices2

COPY ./src/ices/docker/ices-0.4.tar.gz /tmp/ices-0.4.tar.gz
COPY ./src/ices/docker /ices

WORKDIR /tmp
RUN tar xf ices-0.4.tar.gz
WORKDIR /tmp/ices-0.4
RUN ./configure --prefix=/usr/local --with-pic --with-lame --with-python
RUN make
RUN make install clean
RUN mkdir /etc/ices

RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python get-pip.py
RUN pip install redis
COPY ./src/ices/docker/ices.py /usr/local/etc/modules/ices.py

WORKDIR /app

CMD ["/usr/local/bin/ices", "-c", "/ices/ices.conf"]
